services:
  - type: web
    name: allersafe-backend
    env: python
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_S3_BUCKET_NAME
        sync: false
      - key: TAVILY_API_KEY
        sync: false
